<?php
class Services_Block extends AQ_Block {
	
	//set and create block
	function __construct() {
		$block_options = array(
			'name' => 'Services',
			'size' => 'span6',
		);
		
		//create the block
		parent::__construct('services_block', $block_options);
	}
	
	function form($instance) {
		
		$defaults = array(
			'title' => '',
			'desc' => '',
			'icon' => '',
			'link' => '#'
		);
		$instance = wp_parse_args($instance, $defaults);
		extract($instance);
		
		$icons = array (
		   'glass'           =>     'glass',
'music'            =>     'music',
'search'           =>     'search',
'envelope-alt'     =>     'envelope-alt',
'heart'            =>     'heart',
'star'               =>   'star',
'star-empty'            =>'star-empty',
'user'            =>      'user',
'film'            =>      'film',
'th-large'       =>       'th-large',
'th'             =>       'th',
'th-list'        =>       'th-list',
'ok'             =>       'ok',
'remove'        =>        'remove',
'zoom-in'       =>        'zoom-in',
'zoom-out'       =>       'zoom-out',
'off'             =>      'off',
'signal'         =>       'signal',
'gear'          =>        'gear',
'cog'           =>        'cog',
'trash'         =>        'trash',
'home'         =>         'home',
'file-alt'       =>       'file-alt',
'time'           =>       'time',
'road'            =>      'road',
'download-alt'     =>     'download-alt',
'download'        =>      'download',
'upload'         =>       'upload',
'inbox'          =>       'inbox',
'play-circle'     =>      'play-circle',
'repeat'         =>       'repeat',
'refresh'        =>       'refresh',
'list-alt'       =>       'list-alt',
'lock'          =>        'lock',
'flag'         =>         'flag',
'headphones'      =>      'headphones',
'volume-off'      =>      'volume-off',
'volume-down'     =>      'volume-down',
'volume-up'      =>       'volume-up',
'qrcode'         =>       'qrcode',
'barcode'       =>        'barcode',
'tag'           =>        'tag',
'tags'         =>         'tags',
'book'         =>         'book',
'bookmark'      =>        'bookmark',
'print'          =>       'print',
'camera'        =>        'camera',
'font'          =>        'font',
'bold'           =>       'bold',
'italic'         =>       'italic',
'text-height'     =>      'text-height',
'text-width'       =>     'text-width',
'align-left'       =>     'align-left',
'align-center'     =>     'align-center',
'align-right'      =>     'align-right',
'align-justify'     =>    'align-justify',
'list'           =>       'list',
'indent-left'      =>     'indent-left',
'indent-right'      =>    'indent-right',
'facetime-video'    =>    'facetime-video',
'picture'       =>        'picture',
'pencil'         =>       'pencil',
'map-marker'    =>        'map-marker',
'adjust'         =>       'adjust',
'tint'          =>        'tint',
'edit'          =>        'edit',
'share'         =>        'share',
'check'         =>        'check',
'move'          =>        'move',
'step-backward'    =>     'step-backward',
'fast-backward'    =>     'fast-backward',
'backward'      =>        'backward',
'play'           =>       'play',
'pause'          =>       'pause',
'stop'           =>       'stop',
'forward'          =>     'forward',
'fast-forward'     =>     'fast-forward',
'step-forward'      =>    'step-forward',
'eject'            =>     'eject',
'chevron-left'     =>     'chevron-left',
'chevron-right'    =>     'chevron-right',
'plus-sign'       =>      'plus-sign',
'minus-sign'      =>      'minus-sign',
'remove-sign'      =>      'remove-sign',
'ok-sign'          =>     'ok-sign',
'question-sign'    =>     'question-sign',
'info-sign'        =>     'info-sign',
'screenshot'       =>     'screenshot',
'remove-circle'    =>     'remove-circle',
'ok-circle'        =>     'ok-circle',
'ban-circle'      =>      'ban-circle',
'arrow-left'      =>      'arrow-left',
'arrow-right'      =>     'arrow-right',
'arrow-up'         =>     'arrow-up',
'arrow-down'       =>     'arrow-down',
'mail-forward'     =>     'mail-forward',
'resize-full'      =>     'resize-full',
'resize-small'     =>     'resize-small',
'plus'             =>     'plus',
'minus'           =>      'minus',
'asterisk'           =>   'asterisk',
'exclamation-sign'    =>  'exclamation-sign',
'gift'             =>     'gift',
'leaf'              =>    'leaf',
'fire'              =>    'fire',
'eye-open'          =>    'eye-open',
'eye-close'        =>     'eye-close',
'warning-sign'     =>     'warning-sign',
'plane'            =>     'plane',
'calendar'         =>     'calendar',
'random'           =>     'random',
'comment'          =>     'comment',
'magnet'            =>    'magnet',
'chevron-up'        =>    'chevron-up',
'chevron-down'      =>    'chevron-down',
'retweet'            =>   'shopping-cart',
'folder-close'       =>   'folder-close',
'folder-open'        =>   'folder-open',
'resize-vertical'    =>   'resize-vertical',
'resize-horizontal'  =>   'resize-horizontal',
'bar-chart'          =>   'bar-chart',
'twitter-sign'       =>   'twitter-sign',
'facebook-sign'     =>    'facebook-sign',
'camera-retro'      =>    'camera-retro',
'key'               =>    'key',
'gears'             =>    'gears',
'comments'          =>   'comments',
'thumbs-up-alt'      =>   'thumbs-up-alt',
'thumbs-down-alt'    =>   'thumbs-down-alt',
'star-half'          =>   'star-half',
'heart-empty'         =>  'heart-empty',
'signout'             =>  'signout',
'linkedin-sign'       =>  'linkedin-sign',
'pushpin'            =>   'pushpin',
'external-link'      =>   'external-link',
'signin'              =>  'signin',
'trophy'             =>   'trophy',
'github-sign'        =>   'github-sign',
'upload-alt'         =>   'upload-alt',
'lemon'              =>   'lemon',
'phone'              =>   'phone',
'unchecked'          =>   'unchecked',
'bookmark-empty'     =>   'bookmark-empty',
'phone-sign'         =>   'phone-sign',
'twitter'           =>    'twitter',
'facebook'          =>    'facebook',
'github'            =>    'github',
'unlock'            =>    'unlock',
'credit-card'       =>    'credit-card',
'rss'               =>    'rss',
'hdd'                =>   'hdd',
'bullhorn'           =>   'bullhorn',
'bell'               =>   'bell',
'certificate'        =>   'certificate',
'hand-right'         =>   'hand-right',
'hand-left'          =>   'hand-left',
'hand-up'            =>   'hand-up',
'hand-down'         =>    'hand-down',
'circle-arrow-left'   =>  'circle-arrow-left',
'circle-arrow-right'  =>  'circle-arrow-right',
'circle-arrow-up'      => 'circle-arrow-up',
'circle-arrow-down'   =>  'circle-arrow-down',
'globe'             =>    'globe',
'wrench'            =>    'wrench',
'tasks'             =>    'tasks',
'filter'            =>    'filter',
'briefcase'         =>    'briefcase',
'fullscreen'        =>    'fullscreen',
'group'             =>    'group',
'link'              =>    'link',
'cloud'             =>    'cloud',
'beaker'            =>    'beaker',
'cut'               =>    'cut',
'copy'               =>   'copy',
'paperclip'         =>    'paperclip',
'save'              =>    'save',
'sign-blank'        =>    'sign-blank',
'reorder'           =>    'reorder',
'list-ul'           =>    'list-ul',
'list-ol'           =>    'list-ol',
'strikethrough'     =>    'strikethrough',
'underline'         =>    'underline',
'table'             =>    'table',
'magic'             =>    'magic',
'truck'             =>    'truck',
'pinterest'         =>    'pinterest',
'pinterest-sign'     =>   'pinterest-sign',
'google-plus-sign'   =>   'google-plus-sign',
'google-plus'       =>    'google-plus',
'money'              =>   'money',
'caret-down'        =>    'caret-down',
'caret-up'           =>   'caret-up',
'caret-left'         =>   'caret-left',
'caret-right'        =>   'caret-right',
'columns'            =>   'columns',
'sort'               =>   'sort',
'sort-down'         =>    'sort-down',
'sort-up'           =>    'sort-up',
'envelope'          =>    'envelope',
'linkedin'          =>    'linkedin',
'rotate-left'       =>    'rotate-left',
'legal'             =>    'legal',
'dashboard'         =>    'dashboard',
'comment-alt'        =>   'comment-alt',
'comments-alt'        =>  'comments-alt',
'bolt'               =>   'bolt',
'sitemap'            =>   'sitemap',
'umbrella'         =>     'umbrella',
'paste'            =>     'paste',
'lightbulb'        =>     'lightbulb',
'exchange'          =>    'exchange',
'cloud-download'     =>   'cloud-download',
'cloud-upload'      =>    'cloud-upload',
'user-md'          =>    'user-md',
'stethoscope'       =>    'stethoscope',
'suitcase'         =>     'suitcase',
'bell-alt'         =>     'bell-alt',
'coffee'          =>      'coffee',
'food'            =>      'food',
'file-text-alt'     =>    'file-text-alt',
'building'         =>     'building',
'hospital'        =>      'hospital',
'ambulance'        =>     'ambulance',
'medkit'           =>     'medkit',
'fighter-jet'      =>     'fighter-jet',
'beer'             =>     'beer',
'h-sign'           =>     'h-sign',
'plus-sign-alt'     =>    'plus-sign-alt',
'double-angle-left'  =>   'double-angle-left',
'double-angle-right'   => 'double-angle-right',
'double-angle-up'     =>  'double-angle-up',
'double-angle-down'   =>  'double-angle-down',
'angle-left'      =>      'angle-left',
'angle-right'     =>      'angle-right',
'angle-up'          =>    'angle-up',
'angle-down'       =>     'angle-down',
'desktop'          =>     'desktop',
'laptop'          =>      'laptop',
'tablet'          =>      'tablet',
'mobile-phone'     =>     'mobile-phone',
'circle-blank'     =>     'circle-blank',
'quote-left'       =>     'quote-left',
'quote-right'      =>     'quote-right',
'spinner'          =>     'spinner',
'circle'           =>      'circle',
'reply'            =>     'reply',
'github-alt'        =>    'github-alt',
'folder-close-alt'   =>   'folder-close-alt',
'folder-open-alt'    =>   'folder-open-alt',
'expand-alt'         =>   'expand-alt',
'collapse-alt'       =>   'collapse-alt',
'smile'             =>    'smile',
'frown'             =>    'frown',
'meh'              =>     'meh',
'gamepad'          =>     'gamepad',
'keyboard'         =>     'keyboard',
'flag-alt'         =>     'flag-alt',
'flag-checkered'   =>     'flag-checkered',
'terminal'         =>     'terminal',
'code'            =>      'code',
'reply-all'        =>     'reply-all',
'mail-reply-all'  =>     'mail-reply-all',
'star-half-full'    =>    'star-half-full',
'location-arrow'    =>    'location-arrow',
'crop'               =>   'crop',
'code-fork'         =>    'code-fork',
'unlink'            =>    'unlink',
'question'          =>    'info',
'exclamation'      =>     'exclamation',
'superscript'       =>    'superscript',
'subscript'         =>    'subscript',
'eraser'            =>    'eraser',
'puzzle-piece'       =>   'puzzle-piece',
'microphone'        =>    'microphone',
'microphone-off'     =>   'microphone-off',
'shield'             =>   'shield',
'calendar-empty'     =>   'calendar-empty',
'fire-extinguisher'   =>  'fire-extinguisher',
'rocket'            =>    'rocket',
'maxcdn'              =>  'maxcdn',
'chevron-sign-left'   =>  'chevron-sign-left',
'chevron-sign-right'   => 'chevron-sign-right',
'chevron-sign-up'     =>  'chevron-sign-up',
'chevron-sign-down'   =>  'chevron-sign-down',
'html5'              =>   'html5',
'css3'               =>    'css3',
'anchor'           =>     'anchor',
'unlock-alt'       =>     'unlock-alt',
'bullseye'          =>    'bullseye',
'ellipsis-horizontal'  => 'ellipsis-horizontal',
'ellipsis-vertical'   =>  'ellipsis-vertical',
'rss-sign'         =>     'rss-sign',
'play-sign'        =>     'play-sign',
'ticket'          =>      'ticket',
'minus-sign-alt'   =>     'minus-sign-alt',
'check-minus'      =>     'check-minus',
'level-up'        =>      'level-up',
'level-down'      =>      'level-down',
'check-sign'       =>     'check-sign',
'edit-sign'        =>     'edit-sign',
'external-link-sign'   => 'external-link-sign',
'share-sign'         =>   'share-sign',
'compass'           =>    'compass',
'collapse'           =>   'collapse',
'collapse-top'       =>   'collapse-top',
'expand'             =>   'expand',
'euro'             =>     'euro',
'gbp'              =>     'gbp',
'dollar'           =>     'dollar',
'rupee'             =>    'rupee',
'yen'                =>   'yen',
'renminbi'           =>   'renminbi',
'won'                =>   'won',
'bitcoin'            =>   'bitcoin',
'file'               =>   'file',
'file-text'          =>   'file-text',
'sort-by-alphabet'   =>   'sort-by-alphabet',
'sort-by-alphabet-alt' => 'sort-by-alphabet-alt',
'sort-by-attributes-alt' => 'sort-by-attributes-alt',
'sort-by-order'    =>     'sort-by-order',
'sort-by-order-alt'  =>   'sort-by-order-alt',
'thumbs-up'          =>   'thumbs-up',
'thumbs-down'        =>   'thumbs-down',
'youtube-sign'       =>   'youtube-sign',
'youtube'           =>    'youtube',
'xing'              =>    'xing',
'xing-sign'          =>   'xing-sign',
'youtube-play'       =>   'youtube-play',
'dropbox'            =>   'dropbox',
'stackexchange'      =>   'stackexchange',
'instagram'         =>    'instagram',
'flickr'            =>    'flickr',
'adn'               =>    'adn',
'bitbucket'          =>   'bitbucket',
'bitbucket-sign'     =>   'bitbucket-sign',
'tumblr'            =>    'tumblr',
'tumblr-sign'       =>    'tumblr-sign',
'long-arrow-down'   =>    'long-arrow-down',
'long-arrow-up'     =>    'long-arrow-up',
'long-arrow-left'    =>   'long-arrow-left',
'long-arrow-right'   =>   'long-arrow-right',
'apple'             =>    'apple',
'windows'           =>    'windows',
'android'          =>     'android',
'linux'            =>     'linux',
'dribbble'         =>     'dribbble',
'skype'            =>     'skype',
'foursquare'       =>     'foursquare',
'trello'           =>     'trello',
'female'           =>     'female',
'male'             =>     'male',
'gittip'            =>    'gittip',
'sun'               =>    'sun',
'moon'            =>      'moon',
'archive'          =>     'archive',
'bug'              =>     'bug',
'vk'               =>     'vk',
'weibo'            =>     'weibo',
'renren'           =>     'renren'

		);
		
		?>
		<p class="description">
			<label for="<?php echo $this->get_field_id('title') ?>">
				Title
				<?php echo aq_field_input('title', $block_id, $title, $size = 'full') ?>
			</label>
		</p>
		
		<p class="description">
			<label for="<?php echo $this->get_field_id('desc') ?>">
				Description
				<?php echo aq_field_textarea('desc', $block_id, $desc, $size = 'full') ?>
			</label>
		</p>

		<p class="description">
			<label for="<?php echo $this->get_field_id('icon') ?>">
				Choose an Icon<br/>
				<?php echo aq_field_select_icon('icon', $block_id, $icons, $icon); ?>

			</label>
		</p>

		<p class="description">
			<label for="<?php echo $this->get_field_id('link') ?>">
				External link
				<?php echo aq_field_input('link', $block_id, $link, $size = 'full') ?>
			</label>
		</p>		
		
		<?php
	}
	
	function block($instance) {
		extract($instance);

	echo do_shortcode('[services link="'.$link.'" title="'.$title.'" desc="'.$desc.'" icon="'.$icon.'"]');

		
	}
	
}
